CREATE CONSTRAINT IF NOT EXISTS FOR (u:User) REQUIRE u.userId IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (m:Movie) REQUIRE m.movieId IS UNIQUE;

CREATE CONSTRAINT IF NOT EXISTS FOR (g:Genre) REQUIRE g.name IS UNIQUE;

CREATE INDEX IF NOT EXISTS FOR (t:Tagged) ON (t.tag);

CREATE INDEX IF NOT EXISTS FOR (m:Movie) ON (m.imdbId);
CREATE INDEX IF NOT EXISTS FOR (m:Movie) ON (m.tmdbId);
